#!/usr/bin/env bash
# Script to display information about server subdomains

# Function to fetch DNS information for a subdomain
get_dns_info() {
    local domain="$1"
    local subdomain="$2"
    local dns_output=$(dig "$subdomain.$domain" +short)

    if [ -n "$dns_output" ]; then
        local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $dns_output"
    else
        echo "No information found for subdomain $subdomain"
    fi
}

# Main function
main() {
    if [ "$#" -lt 1 ]; then
        echo "Usage: $0 <domain> [subdomain]"
        exit 1
    fi

    local domain="$1"
    local subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -n "$2" ]; then
        get_dns_info "$domain" "$2"
    else
        for subdomain in "${subdomains[@]}"; do
            get_dns_info "$domain" "$subdomain"
        done
    fi
}

# Invoke main function with arguments passed to the script
main "$@"
