#!/usr/bin/env bash
# Display information about subdomains.

# Function to retrieve information about a subdomain
domain_information () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk -v sub="$2" '{print "#student." sub " is a " $2 " record and points to " $3}'
}

# Main script logic
if [ "$#" == 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_information "$1" "$2"
fi
